language: python
python:
  -  "3.8"
before_install:
  - sudo apt install libpq-dev
  - sudo apt-get -qq remove postgis
  - sudo apt-get remove -y libgdal1
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -y
  - sudo apt-get install -y gdal-bin
  - sudo apt install libgdal-dev
install:
  - pip install -r requirements_without_GDAL.txt
  - pip install coverage
script:
  - cd src
  - echo "[run]" >> .coveragerc
  - echo "source = ./" >> .coveragerc
  - coverage run -m unittest discover -s ../test -v
after_success:
  - bash <(curl -s https://codecov.io/bash)