language: python
python:
  -  "3.8"
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  - cd src
  - echo "[run]" >> .coveragerc
  - echo "source = ./" >> .coveragerc
  - coverage run -m unittest discover -s ../test -v
after_success:
  - bash <(curl -s https://codecov.io/bash)