language: python
python:
  -  "3.8"
before_install:
  - sudo apt install libpq-dev
  - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
  - sudo apt-get -qq remove postgis
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install -qq bison flex python-lxml libfribidi-dev swig cmake
    librsvg2-dev colordiff postgis postgresql-9.1-postgis-2.0-scripts libpq-dev
    libpng12-dev libjpeg-dev libgif-dev libgeos-dev libgd2-xpm-dev libfreetype6-
    dev libfcgi-dev libcurl4-gnutls-dev libcairo2-dev libgdal1-dev libproj-dev
    libxml2-dev python-dev php5-dev libexempi-dev lcov lftp
  - sudo apt install gdal-bin
  - sudo apt install libgdal-dev
install:
  - pip install -r requirements_without_GDAL.txt
  - pip install coverage
script:
  - cd src
  - echo "[run]" >> .coveragerc
  - echo "source = ./" >> .coveragerc
  - coverage run -m unittest discover -s ../test -v
after_success:
  - bash <(curl -s https://codecov.io/bash)